[package]
name                   = "cstree"
description            = "Library for generic lossless syntax trees"
categories             = ["parsing", "data-structures"]
keywords               = ["cstree", "parser", "parsing", "cst"]
edition.workspace      = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
readme.workspace       = true
rust-version.workspace = true

[dependencies]
text-size   = "1.1.1"
rustc-hash  = { version = "2.1.1", default-features = false }
parking_lot = "0.12.4"

# Arc
triomphe = { version = "0.1.14", default-features = false, features = ["stable_deref_trait"] }

# HashMap (nostd compatible alternative to std's HashMap)
hashbrown = { version = "0.17.0", default-features = false }

[dependencies.cstree_derive]
path     = "../cstree-derive"
version  = "0.14.0"           # must match the `cstree` version in the virtual workspace manifest
optional = true

[dependencies.serde]
version          = "1.0"
optional         = true
default-features = false
features         = ["derive", "alloc"]

[dev-dependencies]
m_lexer         = "0.0.4"
serde_json      = "1.0"
serde_test      = "1.0"
crossbeam-utils = "0.8.21"
criterion       = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name    = "main"
harness = false

[features]
default = ["std"]
std = ["triomphe/std"]
# Derive macro for `Syntax`
derive = ["dep:cstree_derive"]
# Implementations of `serde::{De,}Serialize` for CSTrees.
serialize = ["serde", "triomphe/serde"]

[[example]]
name              = "math"
required-features = ["derive"]

[[example]]
name              = "s_expressions"
required-features = ["derive"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
